#ifndef CORVINLOGGER_GLOBAL_H
#define CORVINLOGGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CORVINLOGGER_LIBRARY)
#  define CORVINLOGGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CORVINLOGGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CORVINLOGGER_GLOBAL_H
